[project]
name = "web-agent"
version = "0.1.0"
description = "A GUI-grounding agent to locate UI elements from screenshots"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "Apache-2.0" }
dependencies = [
    "transformers>=4.35",
    "torch>=2.1",
    "torchvision>=0.16",
    "pillow>=10.0",
    "accelerate>=1.9.0",
    "websockets>=15.0.1",
    "aiortc>=1.13.0",
    "prometheus-client>=0.22.1",
    "av>=12.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.0", "black>=24.0", "ruff>=0.0"]
docs = ["sphinx>=7.0"]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["uv>=0.8", "setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
py-modules = ["agent"]

[tool.setuptools.packages.find]
where = ["src"]
